# MkDocs configuration for PDF builds
# Usage: mkdocs build -f mkdocs-pdf.yml

INHERIT: mkdocs-base.yml

site_url: "https://docs.percona.com/percona-server/"

# Material theme features
theme:
  name: material
  custom_dir: _resourcepdf/overrides/

extra:
  # Google Analytics configuration
  analytics:
    provider: google
    property: G-J4J70BNH0G
