dirs:
  - docs

ignorePatterns:
  - pattern: "^https://www.reddit.com/r/VictoriaMetrics/"
  - pattern: "^https://linux.die.net/man/8/logrotate"
  - pattern: "#os_alerts$"
  - pattern: "#pmm_alerts$"
  - pattern: "#mongodb_alerts$"
  - pattern: "#pbm_alerts$"
  - pattern: "#mysql_alerts$"
  - pattern: "#postgresql_alerts$"
  - pattern: "#proxysql_alerts$"
  - pattern: "^https://www\\.zmanda\\.com/zrm-community/?$"
  - pattern: "^https://www\\.gnu\\.org/licenses/old-licenses/gpl-2\\.0\\.html/?$"
  - pattern: "^https://www\\.hashicorp\\.com/en/products/vault/?$"

replacementPatterns:
  - pattern: "\\{\\{vers\\}\\}"
    replacement: "9.7"

